### ISSUE TITLE
Marketing for Engineers

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/handbook#6]
# Background

* PostHog helps engineers understand the impact of their work.\
* The world is becoming driven by software.
* It is more impactful than ever that engineers get good at using their skills to help companies grow.
* We would like to produce a guide for how to help engineers build products for growth

# Marketing for Engineers

We would like to produce a guide that will help engineers learn how to help their companies grow.

We will launch this on HN, and aim to reach the front page. That should lead to 20K+ relevant visitors which will help with our organic growth.

Having the guide published on our website, with a series of posts (like a set of docs) will drive longtail SEO traffic, and is something we can add to over time.

# Tone and Style

* The guide needs to be engaging to read. Casual but concise.
* The guide should make use of real life examples to illustrate points made as far as possible. Screenshots or gifs of other websites/applications across a variety of mediums (web/mobile) that make use of product-led growth tactics.
* We should include not just "what" to do but "how" to do it - ie extend the explanations into how to use the PostHog functionality, where applicable
* We should include links to other useful products where PostHog isn't a complete solution, focussing on Open Source products (ideally)

# Useful resources

The two main beliefs I have formed are these two things combined are how companies should grow:

* 101 on what product-led growth is: https://productled.com/product-led-growth-definition/
* How sales cycles actually work now: https://www.hubspot.com/flywheel

# Ideas for sections

* Case studies of product-led growth
* Cover each major stage of the [user lifecycle](https://www.hubspot.com/flywheel):
  * Include key tactics
  * Include examples of this from other companies 
  * Include walk through of how PostHog can help

# Todo

* Create a detailed plan of each section of the guide
* Work out how much needs to be done to be "launch ready". ie I would suggest that we start with some pure case studies for product led growth examples, put that set of posts onto HN first, before we build out the full how to guide.

**Comment by Tannergoods** [comment]
The initial plan for 4 sections.

I will submit a PR with #1 and we can then make that editing conversation transparent


#1 Product Led Growth 

What is it?
Why is it best? (subtext: best for developers) 
How does that reflect onto a sales cycle?
Understand / Attract (Case Study 1?)
Communicate / Engage (Case Study 2?)
Deliver / Delight (Case Study 3?)



#2 Understand / Attract


To attract you must understand
Functional Outcome (core task users need to get done) 
Emotional Outcome (how users feel as a result of executing the above) 
Social Outcome (how users are perceived when using product) 
Metrics to measure this 
Product usage stat
What parts of product / mvp are used most (Trends)
What do people not use (Actions & Funnel)
How do they interact with content (Paths)
Sign ups
UTM tags (cohorts / users)
Referrers (cohorts / users)
Tactics
Channel types
(See ‘Traction’ for a great run through of ~12 channels based on the business type)
Tactics within each channel

#3 Communicate / Engage

To engage you must communicate effectively
Two strands - Revenue model how do you tell people this?
CAM - How good is your product 
Marry these two together (website and app example) 
Measure this - Tactics to improve
Pricing pages - should I have one?
Solution Selling - when communicating to solutions not features


#4 Deliver / Delight

To delight you must deliver
Perceived value vs experienced value - sales led issue of buyer’s remorse 
Closing a value gap
Tactic and Measurement
Stickiness, frequency of usage, “depth” of usage (i.e. how many features a user touches) 
A/B testing - what to measure when you can’t ask / the validity of soft feedback in itself
NPS? - Passive and Active, will they tell you?
Promoters - where is traffic coming from - organic or marketing efforts

#5 Minimizing Friction and Driving Demand round up?
Reassessing the wheel to look for inefficiency?
